CREATE USER(nombre_usuario, password) VALUES ("trolololol@gmail.com", "123");
CREATE USER(nombre_usuario, password) VALUES ("azulgrana@gmail.com", "x123");
CREATE USER(nombre_usuario, password) VALUES ("tyler.durden@gmail.com", "asdfd");

CREATE lista(nombre_lista, fk_id_usuario) VALUES ("romanticona", 0);
CREATE lista(nombre_lista, fk_id_usuario) VALUES ("pesada", 0);
CREATE lista(nombre_lista, fk_id_usuario) VALUES ("pa' bebe'", 0);
CREATE lista(nombre_lista, fk_id_usuario) VALUES ("rock en español", 1);
CREATE lista(nombre_lista, fk_id_usuario) VALUES ("vallenatibiri", 1);
CREATE lista(nombre_lista, fk_id_usuario) VALUES ("para bailar", 2);

CREATE genero(nombre_genero) VALUES("clasica");
CREATE genero(nombre_genero) VALUES("rock");
CREATE genero(nombre_genero) VALUES("pop");
CREATE genero(nombre_genero) VALUES("alternativa");
CREATE genero(nombre_genero) VALUES("cantina");
CREATE genero(nombre_genero) VALUES("bailable");
CREATE genero(nombre_genero) VALUES("vallenato");
CREATE genero(nombre_genero) VALUES("reggae");

CREATE artista(nombre_artista, fecha_nacimiento) VALUES ("Gali Galeano", DATE("01-01-1960"));
CREATE artista(nombre_artista, fecha_nacimiento) VALUES ("Bob Marley", DATE("01-01-1960"));
CREATE artista(nombre_artista, fecha_nacimiento) VALUES ("Vicente Fernandez", DATE("01-02-1955"));
CREATE artista(nombre_artista, fecha_nacimiento) VALUES ("Britney Spears", DATE("05-03-1985"));
CREATE artista(nombre_artista, fecha_nacimiento) VALUES ("Gran Combo", DATE("06-08-1970"));
CREATE artista(nombre_artista, fecha_nacimiento) VALUES ("Ozzy Osbourne", DATE("01-01-1960"));
CREATE artista(nombre_artista, fecha_nacimiento) VALUES ("El Binomio de Oro", DATE("01-01-1985") );
CREATE artista(nombre_artista, fecha_nacimiento) VALUES ("Johann Sebastian Bach", DATE("21-03-1685"));

CREATE album(nombre_album, year) VALUES ("album 1", 1990);
CREATE album(nombre_album, year) VALUES ("album 2", 1991);
CREATE album(nombre_album, year) VALUES ("album 3", 1992);
CREATE album(nombre_album, year) VALUES ("album 4", 1993);
CREATE album(nombre_album, year) VALUES ("album 5", 1994);
CREATE album(nombre_album, year) VALUES ("album 6", 1990);
CREATE album(nombre_album, year) VALUES ("album 7", 1991);
CREATE album(nombre_album, year) VALUES ("album 8", 1992);
CREATE album(nombre_album, year) VALUES ("album 9", 1993);
CREATE album(nombre_album, year) VALUES ("album 10", 1994);


CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 1", 300, "/home/music/cancion1.mp3", 0, 4);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 2", 360, "/home/music/cancion2.mp3", 0, 4);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 3", 320, "/home/music/cancion3.mp3", 0, 5);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 4", 305, "/home/music/cancion4.mp3", 1, 7);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 5", 362, "/home/music/cancion5.mp3", 1, 7);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 6", 323, "/home/music/cancion6.mp3", 1, 7);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 7", 450, "/home/music/cancion7.mp3", 1, 7);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 8", 300, "/home/music/cancion8.mp3", 2, 4);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 9", 360, "/home/music/cancion9.mp3", 2, 4);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 10", 320, "/home/music/cancion10.mp3", 2, 4);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 11", 305, "/home/music/cancion11.mp3", 2, 4);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 12", 362, "/home/music/cancion12.mp3", 2, 4);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 13", 323, "/home/music/cancion13.mp3", 3, 2);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 14", 450, "/home/music/cancion14.mp3", 3, 2);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 15", 300, "/home/music/cancion15.mp3", 4, 5);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 16", 360, "/home/music/cancion16.mp3", 4, 5);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 17", 320, "/home/music/cancion17.mp3", 4, 5);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 18", 305, "/home/music/cancion18.mp3", 4, 5);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 19", 362, "/home/music/cancion19.mp3", 5, 1);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 20", 323, "/home/music/cancion20.mp3", 5, 1);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 21", 111, "/home/music/cancion21.mp3", 5, 3);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 22", 222, "/home/music/cancion22.mp3", 6, 6);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 23", 325, "/home/music/cancion23.mp3", 6, 6);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 24", 320, "/home/music/cancion24.mp3", 6, 6);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 25", 305, "/home/music/cancion25.mp3", 6, 6);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 26", 362, "/home/music/cancion26.mp3", 6, 6);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 27", 156, "/home/music/cancion27.mp3", 6, 6);
CREATE cancion(nombre_cancion, duracion, ruta, fk_id_artista, fk_id_genero) VALUES("Cancion 28", 512, "/home/music/cancion2.mp3", 7, 0);

CREATE cancion_lista VALUES (0, 0);
CREATE cancion_lista VALUES (1, 0);
CREATE cancion_lista VALUES (2, 0);
CREATE cancion_lista VALUES (3, 0);
CREATE cancion_lista VALUES (4, 0);
CREATE cancion_lista VALUES (0, 1);
CREATE cancion_lista VALUES (1, 1);
CREATE cancion_lista VALUES (6, 1);
CREATE cancion_lista VALUES (7, 1);
CREATE cancion_lista VALUES (8, 1);
CREATE cancion_lista VALUES (0, 2);
CREATE cancion_lista VALUES (6, 2);
CREATE cancion_lista VALUES (9, 2);
CREATE cancion_lista VALUES (10, 2);
CREATE cancion_lista VALUES (11, 2);
CREATE cancion_lista VALUES (11, 3);
CREATE cancion_lista VALUES (12, 3);
CREATE cancion_lista VALUES (13, 3);
CREATE cancion_lista VALUES (14, 3);
CREATE cancion_lista VALUES (15, 3);
CREATE cancion_lista VALUES (16, 3);
CREATE cancion_lista VALUES (17, 3);
CREATE cancion_lista VALUES (18, 3);
CREATE cancion_lista VALUES (19, 4);
CREATE cancion_lista VALUES (20, 4);
CREATE cancion_lista VALUES (0, 5);
CREATE cancion_lista VALUES (1, 5);
CREATE cancion_lista VALUES (9, 5);
CREATE cancion_lista VALUES (10, 5);
CREATE cancion_lista VALUES (11, 5);
CREATE cancion_lista VALUES (12, 5);
CREATE cancion_lista VALUES (20, 5);


